# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xty.proto',
  package='com.meiya.ai.grpc.userservice.api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\txty.proto\x12!com.meiya.ai.grpc.userservice.api\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x15\x44\x65\x65pfakeDetectRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xe7\x01\n\x13\x44\x65\x65pfakeDetectReply\x12\x0f\n\x07\x66ileUri\x18\x01 \x01(\t\x12\x0b\n\x03md5\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61taType\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x02\x12\x0e\n\x06\x65uAddr\x18\x05 \x01(\t\x12\x14\n\x0c\x63uEngineAddr\x18\x06 \x01(\t\x12\x16\n\x0e\x63uEngineResult\x18\x07 \x01(\x05\x12\x16\n\x0e\x63uTargetPerson\x18\x08 \x01(\t\x12\x16\n\x0e\x63urrentResults\x18\t \x01(\t\x12\x10\n\x08metaData\x18\n \x01(\t\x12\r\n\x05resTs\x18\x0b \x01(\x03\x32\xfa\x01\n\x0bUserService\x12l\n\x08SayHello\x12/.com.meiya.ai.grpc.userservice.api.HelloRequest\x1a-.com.meiya.ai.grpc.userservice.api.HelloReply\"\x00\x12}\n\x07gxbFace\x12\x38.com.meiya.ai.grpc.userservice.api.DeepfakeDetectRequest\x1a\x36.com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply\"\x00\x62\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='com.meiya.ai.grpc.userservice.api.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.meiya.ai.grpc.userservice.api.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=76,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='com.meiya.ai.grpc.userservice.api.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.meiya.ai.grpc.userservice.api.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=107,
)


_DEEPFAKEDETECTREQUEST = _descriptor.Descriptor(
  name='DeepfakeDetectRequest',
  full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=149,
)


_DEEPFAKEDETECTREPLY = _descriptor.Descriptor(
  name='DeepfakeDetectReply',
  full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileUri', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.fileUri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.md5', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.dataType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.timestamp', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='euAddr', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.euAddr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cuEngineAddr', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.cuEngineAddr', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cuEngineResult', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.cuEngineResult', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cuTargetPerson', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.cuTargetPerson', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentResults', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.currentResults', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metaData', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.metaData', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resTs', full_name='com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply.resTs', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=383,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['DeepfakeDetectRequest'] = _DEEPFAKEDETECTREQUEST
DESCRIPTOR.message_types_by_name['DeepfakeDetectReply'] = _DEEPFAKEDETECTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:com.meiya.ai.grpc.userservice.api.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:com.meiya.ai.grpc.userservice.api.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

DeepfakeDetectRequest = _reflection.GeneratedProtocolMessageType('DeepfakeDetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEEPFAKEDETECTREQUEST,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:com.meiya.ai.grpc.userservice.api.DeepfakeDetectRequest)
  })
_sym_db.RegisterMessage(DeepfakeDetectRequest)

DeepfakeDetectReply = _reflection.GeneratedProtocolMessageType('DeepfakeDetectReply', (_message.Message,), {
  'DESCRIPTOR' : _DEEPFAKEDETECTREPLY,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:com.meiya.ai.grpc.userservice.api.DeepfakeDetectReply)
  })
_sym_db.RegisterMessage(DeepfakeDetectReply)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='com.meiya.ai.grpc.userservice.api.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=386,
  serialized_end=636,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='com.meiya.ai.grpc.userservice.api.UserService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='gxbFace',
    full_name='com.meiya.ai.grpc.userservice.api.UserService.gxbFace',
    index=1,
    containing_service=None,
    input_type=_DEEPFAKEDETECTREQUEST,
    output_type=_DEEPFAKEDETECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
