# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\txty.proto\x12\x06protos\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x05Reply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1f\n\x0cOrderRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\nOrderReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2:\n\tEngineAPI\x12-\n\tengineApi\x12\x0f.protos.Request\x1a\r.protos.Reply\"\x00\x32L\n\nIssueOrder\x12>\n\x10\x45ngineIssueOrder\x12\x14.protos.OrderRequest\x1a\x12.protos.OrderReply\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_ORDERREQUEST = DESCRIPTOR.message_types_by_name['OrderRequest']
_ORDERREPLY = DESCRIPTOR.message_types_by_name['OrderReply']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:protos.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:protos.Reply)
  })
_sym_db.RegisterMessage(Reply)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:protos.OrderRequest)
  })
_sym_db.RegisterMessage(OrderRequest)

OrderReply = _reflection.GeneratedProtocolMessageType('OrderReply', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREPLY,
  '__module__' : 'xty_pb2'
  # @@protoc_insertion_point(class_scope:protos.OrderReply)
  })
_sym_db.RegisterMessage(OrderReply)

_ENGINEAPI = DESCRIPTOR.services_by_name['EngineAPI']
_ISSUEORDER = DESCRIPTOR.services_by_name['IssueOrder']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=21
  _REQUEST._serialized_end=47
  _REPLY._serialized_start=49
  _REPLY._serialized_end=97
  _ORDERREQUEST._serialized_start=99
  _ORDERREQUEST._serialized_end=130
  _ORDERREPLY._serialized_start=132
  _ORDERREPLY._serialized_end=171
  _ENGINEAPI._serialized_start=173
  _ENGINEAPI._serialized_end=231
  _ISSUEORDER._serialized_start=233
  _ISSUEORDER._serialized_end=309
# @@protoc_insertion_point(module_scope)
